# Generated by Django 5.2.5 on 2025-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_plan_duration_subscription_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_boosted_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
