# Generated by Django 5.2.5 on 2025-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
