# Generated by Django 5.2.5 on 2025-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
