# Generated by Django 5.2.5 on 2025-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_scans_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
