# Generated by Django 5.2.5 on 2025-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
