# Generated by Django 5.2.5 on 2025-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_active_premium_user_last_activity_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_premium_days',
            field=models.FloatField(default=0),
        ),
    ]
