# Generated by Django 5.2.5 on 2025-09-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_total_premium_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
