# Generated by Django 5.2.5 on 2025-08-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="User's latitude when the scan was taken", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="User's longitude when the scan was taken", max_digits=9, null=True),
        ),
    ]
