# Generated by Django 5.2.5 on 2025-08-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_scan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='image',
        ),
        migrations.AddField(
            model_name='scan',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
