# Generated by Django 5.2.5 on 2025-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_remove_scan_image_scan_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='location_name',
            field=models.CharField(blank=True, help_text='Location name derived from latitude & longitude', max_length=255, null=True),
        ),
    ]
