# Generated by Django 5.2.5 on 2025-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scan_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scan',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
