# Generated by Django 5.2.5 on 2025-09-01 00:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scan_engagement_score_scan_is_boosted_scan_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_duration_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Duration of scan in minutes, with decimals for seconds.', max_digits=6),
        ),
    ]
