# Generated by Django 5.2.5 on 2025-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_alter_scan_scan_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='source',
            field=models.CharField(choices=[('camera', 'Camera'), ('gallery', 'Gallery')], default='camera', help_text='Source of the scan (camera or gallery)', max_length=10),
        ),
    ]
